### ISSUE TITLE
Build error on "make csi-operator"

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/csi-operator#1]
**Describe the bug**
I just follow the guide [https://github.com/tkestack/csi-operator#build](url) to build binaries, but on command `make csi-operator` getting errors: 

```log
# make csi-operator
go: finding git.tencent.com/tke/csi-operator v0.0.0-20190805030922-5b84a5150d91
Username for 'https://git.tencent.com': ^C
```

it is because the unreachable address, just remove the first line in require section in `go.mod` and re-run the command, the error log is below, looks like lack of appscode/jsonpatch

```log
go fmt ./pkg/... ./cmd/...
build tkestack.io/csi-operator/cmd/csi-operator: cannot load github.com/appscode/jsonpatch: cannot find module providing package github.com/appscode/jsonpatch
make: *** [fmt] Error 1
root
```

**Environment**
 - OS: Linux VM_149_11_centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
 - golang: go version go1.12.4 linux/amd64

**Comment by ruyingzhe** [comment]
The module `appscode/jsonpatch` is no longer exist, official has changed its name.
'appscode/jsonpatch' is depended by `sigs.k8s.io/controller-runtime v0.1.10`

@mlmhl

**Comment by mlmhl** [comment]
@ruyingzhe Thanks!  I have post a [PR](#2 ) to update the go.mod dependencies, could you verify this in your environment?

**Comment by ruyingzhe** [comment]
> @ruyingzhe Thanks! I have post a [PR](#2) to update the go.mod dependencies, could you verify this in your environment?

Verified, the `make csi-operator` command works.
